<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2020/09/14 16:05:20

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=makruuun_user1;host=localhost',
  'profiler' => false,
  'username' => 'makruuun_user1',
  'password' => 'Developpeur123',
  'attributes' => 
  array (
    'quote_identifier' => true,
  ),
  'name' => 'doctrine',
)),);
