<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/09/14 22:12:21
sfConfig::add(array(
  'mod_projectsstatus_enabled' => true,
  'mod_projectsstatus_view_class' => 'sfPHP',
));
