<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/09/17 14:41:50
sfConfig::add(array(
  'mod_projectsreports_enabled' => true,
  'mod_projectsreports_view_class' => 'sfPHP',
));
