<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/09/14 22:13:13
sfConfig::add(array(
  'mod_versionsstatus_enabled' => true,
  'mod_versionsstatus_view_class' => 'sfPHP',
));
