<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/09/15 23:28:40
sfConfig::add(array(
  'mod_projectscomments_enabled' => true,
  'mod_projectscomments_view_class' => 'sfPHP',
));
