<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/09/17 20:10:05
sfConfig::add(array(
  'mod_ticketscomments_enabled' => true,
  'mod_ticketscomments_view_class' => 'sfPHP',
));
