<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/09/13 19:09:24
sfConfig::add(array(
  'mod_accessforbidden_enabled' => true,
  'mod_accessforbidden_view_class' => 'sfPHP',
));
