<?php
// auto-generated by sfSecurityConfigHandler
// date: 2020/09/17 20:10:05
$this->security = array (
  'ldap' => 
  array (
    'is_secure' => false,
  ),
  'restorepassword' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
