<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/09/14 22:13:27
sfConfig::add(array(
  'mod_discussionsstatus_enabled' => true,
  'mod_discussionsstatus_view_class' => 'sfPHP',
));
